package simpledb.execution;

import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {
    private JoinPredicate joinPredicate;
    private TupleDesc tp;

    private OpIterator child1;

    private OpIterator child2;

    // 因为next是一个二重循环结构，所以child1中的tuple不是每次next都要迭代的，用一个字段表示当前应该使用的child1中的tuple
    // 其切换到next的时机是：child2已经完整循环一次了，下次在循环就应该用下一个child1中的tuple了
    // 注意：rewind的时候，要记得给tuple1置为child1的第一个tuple
    private Tuple tuple1 = null;

    private static final long serialVersionUID = 1L;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        this.joinPredicate = p;
        this.child1 = child1;
        this.child2 = child2;
        this.tp = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public JoinPredicate getJoinPredicate() {
        return joinPredicate;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        return child1.getTupleDesc().getFieldName(joinPredicate.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        return child2.getTupleDesc().getFieldName(joinPredicate.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return tp;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        child1.open();
        child2.open();
        if(child1.hasNext()){
            tuple1 = child1.next();
        }
        super.open();
    }

    public void close() {
        super.close();
        tuple1 = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
        if(child1.hasNext()){
            tuple1 = child1.next();
        }
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        while (tuple1 != null) {
            if (!child2.hasNext()) {
                if (child1.hasNext()) {
                    tuple1 = child1.next();
                    child2.rewind();
                } else {
                    return null;
                }
            }
            while (child2.hasNext()) {
                Tuple tuple2 = child2.next();
                if (joinPredicate.filter(tuple1, tuple2)) {
                    Tuple tuple = new Tuple(tp);
                    for (int i = 0; i < tp.numFields(); i++) {
                        if (i < child1.getTupleDesc().numFields()) {
                            tuple.setField(i, tuple1.getField(i));
                        } else {
                            tuple.setField(i, tuple2.getField(i - child1.getTupleDesc().numFields()));
                        }
                    }
                    return tuple;
                }
            }
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        return new OpIterator[]{child1,child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        child1 = children[0];
        child2 = children[1];
    }

}
